GET http://localhost:3000/

###
POST http://localhost:3000/posts
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFhMjA0ODllZDA4ZDIzNjgzMDc0OGUiLCJpYXQiOjE2MjkyMDkxOTF9.UHZEGW4mKqLXlg_dT8JBQPiJaPC6zWYJryCcd2VsJHA

{
    
    "title":"deneme12345",
    "message":"deneme12345"
}

###
GET http://localhost:3000/posts
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFhMjA0ODllZDA4ZDIzNjgzMDc0OGUiLCJpYXQiOjE2MjkyMDkxOTF9.UHZEGW4mKqLXlg_dT8JBQPiJaPC6zWYJryCcd2VsJHA


###

GET http://localhost:3000/posts/612384e43cc9234dbcaa2d5f

###

PUT http://localhost:3000/posts/123

###

DELETE http://localhost:3000/posts/611133f946f39963b8779639
Content-Type: application/json

###

PUT  http://localhost:3000/posts/611d0282c07d9a01acf4f686
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFlMTkwM2JkYzhjMjJmMjhhZGM5ZDIiLCJpYXQiOjE2Mjk3MTc1MTV9.A3QTknkR-hoexWPg92YR0JlM0Zba89Nwq1bvpWmZkFw

{
    
    "title":"deneme2asdaasdad",
    "message":"deneme2"
    
}

###
POST http://localhost:3000/posts/comments
Content-Type: application/json

{
    "userName":"selammm",
    "title":"baslik",
    "message":"selammm"
}

###
GET http://localhost:3000/posts/comments



###


DELETE http://localhost:3000/posts/comments/611135dcad80c448188d74ba
Content-Type: application/json

###
GET http://localhost:3000/posts/61113e9d70f35b5c24be36a7/comments

###
GET http://localhost:3000/auth

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{    
    "name":"onur",
    "userName":"on2222",
    "email":"onr1992222@email.com",
    "password":"19onuasd"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{    
    
    "username":"onur12345",
    "password":"onur12345",
    
}

###
POST http://localhost:3000/posts/611cd6520c636d3368e30f0c/comments
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFiOWQ1NTEwZTQ2MDA1ODgxMjdmZjkiLCJpYXQiOjE2MjkyNzA3MzR9.lXc9ApF5RhCS2i1HKAvEGvFIDxv51sACAY6lvu3eVro

{    
    "message":"selam"
}

###
POST  http://localhost:3000/auth/username
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFiOWQ1NTEwZTQ2MDA1ODgxMjdmZjkiLCJpYXQiOjE2MjkyNzA3MzR9.lXc9ApF5RhCS2i1HKAvEGvFIDxv51sACAY6lvu3eVro

###

GET http://localhost:3000/profile
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFlMTkwM2JkYzhjMjJmMjhhZGM5ZDIiLCJpYXQiOjE2MjkzNjgzNDV9.FDaPGyiTpysWS9t_q_Ng9yCsDZ66MVwjZeFUknqw6Ec

###

GET http://localhost:3000/profile/posts
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTFlMTkwM2JkYzhjMjJmMjhhZGM5ZDIiLCJpYXQiOjE2MjkzNjgzNDV9.FDaPGyiTpysWS9t_q_Ng9yCsDZ66MVwjZeFUknqw6Ec