GET http://localhost:3000/

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "userName":"kullanıcı",
    "title":"deneme12345",
    "message":"deneme12345"
}

###
GET http://localhost:3000/posts



###

GET http://localhost:3000/posts/611100daf471052018ede970

###

PUT http://localhost:3000/posts/123

###

DELETE http://localhost:3000/posts/611133f946f39963b8779639
Content-Type: application/json

###

PUT  http://localhost:3000/posts/610d47305ab4583110922c8d
Content-Type: application/json

{
    "userName":"deneme2",
    "title":"deneme2",
    "message":"deneme2"
    
}

###
POST http://localhost:3000/posts/comments
Content-Type: application/json

{
    "userName":"selam",
    "title":"selam",
    "message":"selam"
}

###
GET http://localhost:3000/posts/comments



###


DELETE http://localhost:3000/posts/comments/611135dcad80c448188d74ba
Content-Type: application/json

###
GET http://localhost:3000/posts/comments/yorumlar